language: go

go:
  - "1.10.x"

services:
  - docker

install:
  - make build-tools

script:
  - make lint
  - make test-unit
  - make build
  - make test-functional
  - gocovmerge coverage.functional.out coverage.out > combined.out
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=combined.out
